jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - 
        id: go
        name: "Set up Go 1.13"
        uses: actions/setup-go@v1
        with: 
          go-version: 1.13
      - 
        name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: us-east-2
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-session-token: "${{ secrets.AWS_SESSION_TOKEN }}"
      - 
        name: "Check out code into the Go module directory"
        uses: actions/checkout@v2.0.0
      - 
        name: "Check out submodules"
        uses: textbook/git-checkout-submodule-action@2.0.0
      - 
        name: "Get dependencies"
        run: |
            go get -v -t -d ./...
            if [ -f Gopkg.toml ]; then
                curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
                dep ensure
            fi
      - 
        name: Build
        run: "go build -v ./..."
      - 
        name: "Test with coverage"
        run: "go test -v ./... -coverprofile coverage.txt"
      - 
        name: "Upload Coverage report to CodeCov"
        uses: codecov/codecov-action@v1
        with: 
          file: ./coverage.txt
          token: "${{secrets.CODECOV_TOKEN}}"
  imports: 
    name: goimports
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@master
      - 
        name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with: 
          run: imports
          token: "${{ secrets.GITHUB_TOKEN }}"
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@master
      - 
        name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with: 
          run: lint
          token: "${{ secrets.GITHUB_TOKEN }}"
name: "Go Build"
true: 
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master
